services:
  - type: web
    name: testmatrics
    env: docker
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_URL
        value: https://testmatrics.onrender.com
      - key: DB_CONNECTION
        value: pgsql
