services:
  - type: web
    name: testmatrics
    env: node
    plan: free
    branch: master
    buildCommand: |
      composer install --no-progress --no-suggest --prefer-dist
      npm ci
      npm run build
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: 'false'
      - key: APP_URL
        value: https://testmatrics.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromService:
          name: testmatrics-db
          type: postgresql
